CREATE TABLE AQ$_SHARED_Q_TAB_G
   (	MSGID RAW(16),
	SUBSCRIBER# NUMBER,
	NAME VARCHAR2(512),
	ADDRESS# NUMBER,
	SIGN SYS.AQ$_SIG_PROP ,
	DBS_SIGN SYS.AQ$_SIG_PROP ,
	 PRIMARY KEY (MSGID, SUBSCRIBER#, NAME, ADDRESS#) ENABLE
   ) USAGE QUEUE ORGANIZATION INDEX NOCOMPRESS  INCLUDING SIGN OVERFLOW;

