CREATE TABLE AQ$_SHARED_Q_TAB_T
   (	NEXT_DATE TIMESTAMP (6),
	TXN_ID VARCHAR2(30),
	MSGID RAW(16),
	ACTION NUMBER,
	 PRIMARY KEY (NEXT_DATE, TXN_ID, MSGID) ENABLE
   ) USAGE QUEUE ORGANIZATION INDEX NOCOMPRESS ;

