CREATE OR REPLACE FORCE EDITIONABLE VIEW AQ$SHARED_Q_TAB_S (QUEUE, NAME, ADDRESS, PROTOCOL, TRANSFORMATION, QUEUE_TO_QUEUE) AS
  SELECT queue_name QUEUE, name NAME , address ADDRESS , protocol PROTOCOL, trans_name TRANSFORMATION, decode(bitand(SUBSCRIBER_TYPE, 512), 512, 'TRUE', 'FALSE') QUEUE_TO_QUEUE  FROM AQ$_SHARED_Q_TAB_S s  WHERE (bitand(s.subscriber_type, 1) = 1)  WITH READ ONLY;

